version: "3.9"

services:
  telegram-bot:
    container_name: telegram_bot
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: telegram_bot_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo
